.gitignore, server/Dockerfile, server/package.json, server/src/routes/BundlesRouter.ts
=> dockerfile

client/src/context/UserProvider.tsx
Add control if the provider is not present in the browser 
Related to Issue #43
=> provider not present

client/src/+assets/details.tsx
Adds debug on asset loading, working locally but not in the server
=> details debug

client/Dockerfile, client/src/+assets/details.tsx
Remove package lock from Dockerfile
=> package lock

server/src/models/Dataset.ts, server/src/routes/BundlesRouter.ts
Add file name to the server endpoint
=> add file name

client/pages/checkout.tsx, client/public/assets/close.svg, client/src/+assets/assets-list.module.scss, client/src/+assets/assets-list.tsx, client/src/+assets/checkout.module.scss, client/src/+assets/checkout.tsx, client/src/components/+assets-query/assets-query.tsx, client/src/components/layout/layout.module.scss, client/src/components/layout/layout.tsx, client/src/context/UserProvider.test.ts, client/src/context/UserProvider.tsx, client/src/context/index.tsx
Add checkout flow. Kind of a WIP PR to unblock @fabriziogianni7 . there's important details left like, adding a modal for adding assets to the basket.
=> New checkout flow

client/src/components/+assets-query/assets-query.tsx
Exclude bundles from search list
=> exlude bundle

client/src/components/+create-bundle/popup/create-bundle-popup.tsx, client/src/config.ts, client/src/shared/api.ts, server/src/controllers/bundles.ts, server/src/routes/BundlesRouter.ts
Checks bundle status until zip is generated or threshold reached
=> check bundle status

client/src/context/UserProvider.tsx
alert asking to install metamask if it is not installed.
Modified loginMetamask on wallet.tsx
=> alert to install MM on CONNECT WALLET button click

client/src/context/MetamaskProvider.ts
add chainName and correctNetworkURL to addNetwork() according to https://docs.metamask.io/guide/rpc-api.html#unrestricted-methods 
needed to switch chain to mumbai
=> add chainName and correctNetworkURL to addNetwork

client/pages/_app.tsx, client/src/+about/about.tsx, client/src/+assets/landing.tsx, client/src/config.ts
=> about text

client/src/+assets/details.tsx
Add sample button in description and add to cart instead of download
=> samples and cart

client/src/+assets/history.tsx, client/src/components/+buy-asset/buy-asset.tsx, client/src/components/+buy-asset/popup/buy-asset-popup.tsx, client/src/config.ts, client/src/shared/api.ts, server/src/controllers/bundles.ts, server/src/index.ts, server/src/routes/UserRouter.ts
=> profile data

client/src/+assets/details.tsx
Changes description to ad new line on dataset fields
=> desciption new line

client/src/+about/about.tsx, client/src/components/+assets-query/search-bar.tsx
=> change text

client/src/+cli/cli.tsx
The CLI get command orders the asset so we can simplify a bit the details given to the user
=> Small cli clarifications

client/src/+assets/details.tsx, client/src/+cli/cli.tsx, client/src/components/markdown/markdown.module.scss, client/src/components/markdown/markdown.tsx
Adds markdown to detail page and changes cli to only show one command per markdown
=> markdown detail & fixes

client/src/+assets/checkout.tsx
=> cart price

client/src/+assets/checkout.tsx
Removes purchase button if the cart is empty
=> disable purchase button

client/src/+assets/profile.tsx
if there are no orders, show "no orders yet" instead of the table header
closes #138
=> if there are no orders, show "no orders yet"

client/src/+assets/details.module.scss, client/src/+assets/details.tsx
loadspinner when loading assets
closes #143
=> loadspinner

client/src/components/+assets-query/filter-dropdown/price-range-selector.tsx
ui fix on price selector
closes #141
=> remove label

client/src/+assets/landing.tsx, client/src/components/+create-bundle/popup/create-bundle-popup.module.scss, client/src/components/+create-bundle/popup/create-bundle-popup.tsx
=> pop up styling

client/src/+status/status.module.scss, client/src/+status/status.tsx
status page implemented
closes #137
=> status page

client/package.json, client/src/+assets/profile.tsx, client/src/config.ts
Add subgraph support to retrive already purchased assets in profile
=> subgraph integration

client/src/+assets/profile.tsx
=> fix userAccount

client/src/+assets/added-to-basket-popup.module.scss, client/src/+assets/added-to-basket-popup.tsx, client/src/+assets/assets-list.module.scss, client/src/+assets/assets-list.tsx, client/src/+assets/details.module.scss, client/src/+assets/details.tsx
added to basket popup in details page
closes #121
=> added to basket popup

client/src/context/UserProvider.tsx
=> fix error message if wallet doesn't connect to mumbai

client/src/+assets/profile.tsx
Fix missing user account on download asset
=> fix user account

client/src/components/+buy-asset/popup/buy-asset-popup.module.scss, client/src/components/+buy-asset/popup/buy-asset-popup.tsx
=> popup profile

client/src/+assets/profile.tsx
Fix profile without wallet error
=> profile without wallet

client/src/+assets/profile.module.scss, client/src/+assets/profile.tsx
=> implement bundle details

client/src/components/+create-bundle/popup/create-bundle-popup.tsx, client/src/components/loaders/loader.module.scss, client/src/components/loaders/loader.tsx
=> Fix loader position

client/src/+assets/details.tsx
=> change circle loader icon to triangle

client/src/+assets/profile.module.scss, client/src/+assets/profile.tsx
=> set format to bundle details

client/src/+assets/profile.module.scss, client/src/+assets/profile.tsx, client/src/components/+create-bundle/popup/create-bundle-popup.tsx
Changes spinner style in the profile and sort bundles by creation date
=> spinner style and sort

client/src/+assets/profile.tsx, client/src/config.ts
=> entity name

client/src/components/+create-bundle/popup/create-bundle-popup.tsx
=> download view

client/pages/404.tsx, client/src/+errors/404.module.scss, client/src/+errors/404.tsx
=> add 404 page

.gitignore, client/src/+assets/checkout.tsx, client/src/components/+create-bundle/create-bundle.tsx, client/src/components/+create-bundle/popup/create-bundle-popup.tsx, client/src/shared/api.ts, server/src/controllers/bundles.ts, server/src/models/Bundle.ts, server/src/routes/BundlesRouter.ts
Add did as dataset ID and bundle price
=> datatset id and price

client/src/components/+buy-asset/popup/buy-asset-popup.tsx
Changes purchased pop up in profile page
=> purchased popup

client/src/+assets/checkout.tsx
=> check network before purchase

client/pages/_app.tsx, client/src/components/header/header.tsx, client/src/config.ts
Add docs link and fixes env var names
=> docs link and config fixes

.github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/feature_ticket.md
=> add feature ticket template

.github/ISSUE_TEMPLATE/feature_ticket.md
=> short description

client/public/assets/ellipse.svg, client/src/+assets/details.module.scss, client/src/+assets/details.tsx, client/src/+assets/profile.tsx, client/src/config.ts, client/src/shared/utils.ts
=> implement provenance ui in asset details

client/src/+assets/profile.tsx
this is regarding to this ticket https://github.com/nevermined-io/defi-marketplace/issues/206
=> improve filter behavior in profile

client/package.json
Changes package json to load env vars on app starts 
=> build & start

client/src/+assets/details.tsx, client/src/+assets/profile.tsx, client/src/config.ts, client/src/shared/api.ts, client/src/shared/graphql.ts, server/src/controllers/bundles.ts, server/src/routes/BundlesRouter.ts
Add provenance info from db + subgraph
=> provenance info

client/package.json, client/src/context/UserProvider.tsx
Changes nvm dependencies and graph url
=> graph & version

client/package-lock.json, client/pages/_app.tsx, client/src/components/header/header.tsx
=> add google analytics

client/src/+assets/details.tsx, client/src/config.ts, client/src/shared/api.ts, server/src/controllers/samples.ts, server/src/index.ts, server/src/models/Sample.ts, server/src/routes/SampleRouter.ts
Creates a new endpoint and get samples URL from DB
=> samples api

client/src/components/+assets-query/assets-query.tsx
=> filter no listed assets

client/src/+assets/profile.tsx, client/src/components/+download-asset/popup/download-asset-popup.module.scss, client/src/components/+download-asset/popup/download-asset-popup.tsx
download asset popup & pointer on download icon
Closes #213 
Closes #214
=> wrapping image in div

client/next.config.js, client/package-lock.json, client/package.json, client/src/config.ts, client/src/context/UserProvider.tsx
Implement login to Marketplace API
=> Implement login

client/src/+assets/profile.tsx, client/src/+assets/user-profile.module.scss, client/src/+assets/user-profile.tsx
UI and UX refactor in Account and Bookmark
=> UI and UX refactor in Account and Bookmark

client/package-lock.json, client/package.json
We need to decide what node version to use #266 
I also pinned the version of the sdk. Expect breaking changes to happen between version
=> Fix package-lock.json

.github/workflows/release-github.yml, README.md
- Added a release workflow that will automatically update the changelog and create a github release everytime we push a tag into the branch
- Updated the README with instructions of how to do a release
=> Added release workflow

client/src/+assets/user-publish-steps/basic-info.tsx, client/src/+assets/user-publish-steps/details.tsx, client/src/+assets/user-publish-steps/files.tsx, client/src/+assets/user-publish-steps/prices.tsx, client/src/+assets/user-publish-steps/user-publish.module.scss
=> form colors

docs/stylesheets/extra.css
=> color scheme

mkdocs.yml
=> extra css position

client/pages/_app.tsx, client/pages/subscription.tsx, client/src/+assets/subscription.module.scss, client/src/+assets/subscription.tsx, client/src/components/+subscription/pricing.module.scss, client/src/components/+subscription/pricing.tsx
Creates the subscription page with tiers detail
=> subscription page

client/src/+assets/user-publish-steps/files.tsx, client/src/+assets/user-publish-steps/main-page.tsx, client/src/+assets/user-publish-steps/prices.tsx, client/src/+assets/user-publish-steps/progress-popup.tsx, client/src/components/+create-bundle/popup/create-bundle-popup.tsx
Deals with  the publish nft tx in an async way
=> sending tx in async way

client/src/+assets/user-publish-steps/main-page.tsx
updating status on submit action to hide the form elements before showing the tx popup
=> updating publish status right on submit

client/src/+assets/user-publish-steps/main-page.tsx, client/src/+assets/user-publish-steps/prices.tsx, client/src/+assets/user-publish-steps/result-popup.tsx
It shows the result of the publish flow in a popup
=> publish result in a popup

client/package-lock.json, client/package.json, client/pages/_app.tsx, client/src/+assets/account.tsx, client/src/+assets/assets-list.tsx, client/src/+assets/user-publish-steps/basic-info.tsx, client/src/+assets/user-publish-steps/files-handler.ts, client/src/+assets/user-publish-steps/main-page.tsx, client/src/+assets/user-publish-steps/prices.tsx, client/src/components/+assets-query/assets-query.tsx, client/src/config.ts, client/src/context/UserProvider.tsx, client/src/context/index.tsx, client/src/shared/utils.ts
- Fix bookmark behavior
- fix error list undefined
- Improve modal messages
- Update catalog and provider versions
- Import from catalog is more idiomatic
- Show logs in browser console
=> fix minor issues

client/package-lock.json, client/package.json, client/pages/_app.tsx, client/src/+assets/account.tsx, client/src/+assets/added-to-basket-popup.tsx, client/src/+assets/assets-list.tsx, client/src/+assets/details.tsx, client/src/+assets/user-profile.tsx, client/src/+assets/user-publish-steps/basic-info.tsx, client/src/+assets/user-publish-steps/details.tsx, client/src/+assets/user-publish-steps/files.tsx, client/src/+assets/user-publish-steps/main-page.tsx, client/src/+assets/user-publish-steps/prices.tsx, client/src/+status/status.tsx, client/src/components/+assets-query/assets-query.tsx, client/src/components/+buy-asset/popup/buy-asset-popup.tsx, client/src/components/+create-bundle/popup/create-bundle-popup.tsx, client/src/components/+subscription/pricing.tsx, client/src/context/UserProvider.tsx
update Catalog version and address all the breaking changes
=> update Catalog version and address all the breaking changes

client/public/assets/subscription-tick.svg, client/src/+assets/subscription.tsx, client/src/components/+subscription/pricing.module.scss, client/src/components/+subscription/pricing.tsx
=> subscription design

client/src/+assets/user-publish-steps/confirm-popup.tsx, client/src/+assets/user-publish-steps/popup.module.scss, client/src/components/+subscription/pricing.module.scss
=> confirm logo

client/src/+assets/user-profile.module.scss, client/src/+assets/user-profile.tsx
=> profile design

client/src/config.ts
Modify subscription ids with newer subscriptions of 15770000 blocks duration 
=> subscription duration

.github/workflows/build.yml, client/pages/_app.tsx, client/src/+about/diagram.tsx, client/src/+assets/account.tsx, client/src/+assets/assets-list.tsx, client/src/+assets/details.tsx, client/src/+assets/user-profile.tsx, client/src/+assets/user-publish-steps/main-page.tsx
Fixes build errors and create build task
=> build errors

client/src/config.ts
=> rename env vbles with NEXT_PUBLIC prefix

client/src/+assets/account.tsx, client/src/+assets/assets-list.module.scss, client/src/+assets/assets-list.tsx, client/src/+assets/subscription.tsx, client/src/+assets/user-profile.module.scss, client/src/+assets/user-profile.tsx, client/src/components/+account/account.module.scss, client/src/components/+account/subscriptions.module.scss, client/src/components/+account/subscriptions.tsx, client/src/components/+account/summary.tsx, client/src/components/+assets-query/assets-query.tsx, client/src/components/subscription-badge/subscription-badge.module.scss, client/src/components/subscription-badge/subscription-badge.tsx, client/src/context/UserProvider.tsx, client/src/context/index.tsx
The PR introduces the following changes:
* slightly improved Account / Dashboard page
* reorganized fields in Account / Profile according to Figma
* hides category and bookmark columns in Account / Purchases
* implements design of Account / Subscription according to Figma
https://user-images.githubusercontent.com/1643399/191346094-9025982b-4601-422a-85bf-e0d8869ffbfc.mov
Related to Issue #362
=> Account layout adjustments

client/src/+assets/user-publish-steps/main-page.tsx
adds default curation metadata when users publish a new asset
=> add default curation to metadata

client/package-lock.json, client/package.json, client/src/+assets/user-publish-steps/main-page.tsx
integrates latest version of catalog
=> integrate catalog 0.2.0

client/src/+assets/assets-list.module.scss, client/src/+assets/assets-list.tsx, client/src/components/+account/account.module.scss, client/src/components/+account/summary.tsx, client/src/components/subscription-badge/subscription-badge.module.scss, client/src/components/subscription-badge/subscription-badge.tsx
=> Layout issues

client/src/components/+assets-query/assets-query.tsx, client/src/components/+assets-query/filter-dropdown/filter-dropdown.module.scss, client/src/components/+assets-query/filter-dropdown/filter-dropdown.tsx, client/src/components/+assets-query/filter-dropdown/subscription-box.tsx, client/src/components/+assets-query/search-bar.tsx, client/src/components/subscription-badge/subscription-badge.tsx, client/src/context/UserProvider.tsx, client/src/context/index.tsx
Implements filter layout and functionality according to Figma design.
https://user-images.githubusercontent.com/1643399/191554029-c9b93380-142b-4797-89cf-e2ddf75cf277.mov
Please take note that I changed the current filter functionality and it will no longer make a search query as user selects a filter, now the user has to explicitly click Apply Filters button instead.
Related to Issue #361
=> Filters layout

client/src/+assets/assets-list.tsx
Checks if the user is already logged in to load their data on listing
=> check is logged in

client/src/+assets/user-publish-steps/files.tsx, client/src/+assets/user-publish-steps/main-page.tsx, client/src/components/+download-asset/popup/download-asset-popup.tsx, client/src/components/+subscription/pricing.tsx
improves the messages showed in popups and alerts for more clarity
=> change messages in popups and alerts

client/src/+assets/account.tsx, client/src/+assets/assets-list.tsx, client/src/components/+download-asset/popup/download-asset-popup.tsx
Removes the legacy code in asset listing for batch purchase
=> removing legacy code for batch purchase

client/src/+assets/details.module.scss, client/src/+assets/details.tsx, client/src/components/markdown/markdown.module.scss, client/src/components/markdown/markdown.tsx
Fixes layout to match the Figma design.
https://user-images.githubusercontent.com/1643399/191992695-f87a4f79-20fb-4702-a168-8f7881296ce7.mov
Related to Issue #357
=> Asset details layout

client/src/+assets/details.tsx
adds the download action in the asset details page
=> download action in details

client/src/+assets/assets-list.tsx, client/src/+assets/details.tsx
show inactive subscription badge in asset listing and details if the user has not that subscription active
=> inactive badges if not subscription

client/src/+assets/landing.tsx
changes texts in landing page to remove references to purchase assets
=> change texts in landing page

client/public/assets/cursor-pointer.svg, client/src/+assets/landing.module.scss, client/src/+assets/landing.tsx
Minor positioning fix
https://user-images.githubusercontent.com/1643399/192517072-917a29b5-f400-43b0-b9f6-f672abf623ef.mov
=> Landing page fix

client/src/+assets/landing.module.scss
I forgot to add the numbers gradient 🤦
=> Landing page numbers gradient

client/src/components/+subscription/pricing.module.scss, client/src/components/+subscription/pricing.tsx, client/src/context/UserProvider.tsx, client/src/context/index.tsx
=> disable tiers

client/package.json, client/src/+assets/account.tsx, client/src/+assets/assets-list.tsx, client/src/+assets/user-profile.tsx, client/src/components/+assets-query/assets-query.tsx
closes automatically the log error popup when user signs the message with metamask
deals with exceptions using the marketplace-api
=> close log error popup automatically and  deal with markeplace-api exceptions

client/package-lock.json, client/package.json, client/src/+assets/account.tsx, client/src/+assets/assets-list.tsx, client/src/components/+subscription/pricing.tsx, client/src/config.ts, client/src/shared/utils.ts
- Updates catalog version
- Updates tier address
=> catalog version and tier

client/src/+assets/details.tsx, client/src/components/+assets-query/assets-query.tsx, client/src/shared/utils.ts
=> nft access service

client/Dockerfile, client/package-lock.json, client/package.json, client/pages/_app.tsx, client/src/+assets/account.tsx, client/src/+assets/assets-list.tsx, client/src/+assets/details.tsx, client/src/+assets/user-profile.tsx, client/src/+assets/user-publish-steps/files-handler.ts, client/src/+assets/user-publish-steps/main-page.tsx, client/src/+status/status.tsx, client/src/components/+assets-query/assets-query.tsx, client/src/components/+subscription/pricing.tsx, client/src/components/+token-name/token-name.tsx, client/src/components/+wallet/wallet.tsx, client/src/config.ts, client/src/context/UserProvider.tsx, client/src/shared/graphql.ts
=> catalog version

client/Dockerfile, client/package-lock.json, client/package.json, client/pages/_app.tsx, client/src/config.ts
Checks if the wallet network is supported in a specific deployment
=> supported network

client/src/+assets/user-publish-steps/files-handler.ts, client/src/+assets/user-publish-steps/main-page.tsx, client/src/config.ts
=> upload filecoin catalog
